In [147]:
import pandas as pd

In [148]:
df= pd.read_excel(r"C:\Users\Monsruti Devi\Documents\DRUG DISCOVERY PROJECT\Book1.xlsx", header= None)
df

,0,1,2
0,Column1,Column2,Column3
1,NaN,NaN,NaN
2,S No.,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,1.,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,2.,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,3.,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,4.,"Bruceoside B^1,2",-
7,5.,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,6.,"Soulameanone 1,2",-
9,7.,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,8.,"Bruceolline A 1,2",-
11,9.,"Bruceolline B 1,4",-
12,10.,"Bruceolline C 1,2",-
13,11.,"Bruceolline D 1,2",-
14,12.,"Bruceolline E 1,2",-
15,13.,"Bruceolline F 1,2",-
16,14.,"Bruceolline G 1,2",-
17,15.,"5,11-Dimethoxycanthin-6-one 1,2",-
18,16.,11-Hydroxycanthin-6-one N-oxide 2,-
19,17.,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,18.,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,19.,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,20.,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,21.,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,22.,"Canthin-6-one N –oxide 1,2",-
25,23.,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,"glucopyranosylcanthin-6-one 1,2",-,NaN
27,24.,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,"glucopyranosylcanthin-6-one 1,2",-,NaN
29,25.,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,26.,Bruceollines H-N 122 6,NaN
31,27.,Bruceollines H-N 222 6,NaN
32,28.,Bruceollines H-N 322 6,NaN
33,29.,Bruceollines H-N 422 6,NaN
34,30.,Bruceollines H-N 522 6,NaN
35,31.,Bruceollines H-N 622 6,NaN
36,32.,Bruceollines H-N 722 6,NaN
37,33.,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,34.,Yadanziolides T-V 1122 6,NaN
39,35.,Yadanziolides T-V 1222 6,NaN
40,36.,Bruceolline E22 6,NaN
41,37.,Bruceolline F22 6,NaN
42,38.,Bruceine D22 6,Cytotoxic22 6
43,39.,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,40.,Yadanziolide B22 6,Cytotoxic22 6
45,41.,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

In [149]:
df2= df.iloc[26,1]= "glucopyranosylcanthin-6-one 1,2"
df3= df.iloc[28,1]= "glucopyranosylcanthin-6-one 1,2"
df

,0,1,2
0,Column1,Column2,Column3
1,NaN,NaN,NaN
2,S No.,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,1.,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,2.,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,3.,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,4.,"Bruceoside B^1,2",-
7,5.,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,6.,"Soulameanone 1,2",-
9,7.,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,8.,"Bruceolline A 1,2",-
11,9.,"Bruceolline B 1,4",-
12,10.,"Bruceolline C 1,2",-
13,11.,"Bruceolline D 1,2",-
14,12.,"Bruceolline E 1,2",-
15,13.,"Bruceolline F 1,2",-
16,14.,"Bruceolline G 1,2",-
17,15.,"5,11-Dimethoxycanthin-6-one 1,2",-
18,16.,11-Hydroxycanthin-6-one N-oxide 2,-
19,17.,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,18.,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,19.,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,20.,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,21.,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,22.,"Canthin-6-one N –oxide 1,2",-
25,23.,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,"glucopyranosylcanthin-6-one 1,2","glucopyranosylcanthin-6-one 1,2",NaN
27,24.,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,"glucopyranosylcanthin-6-one 1,2","glucopyranosylcanthin-6-one 1,2",NaN
29,25.,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,26.,Bruceollines H-N 122 6,NaN
31,27.,Bruceollines H-N 222 6,NaN
32,28.,Bruceollines H-N 322 6,NaN
33,29.,Bruceollines H-N 422 6,NaN
34,30.,Bruceollines H-N 522 6,NaN
35,31.,Bruceollines H-N 622 6,NaN
36,32.,Bruceollines H-N 722 6,NaN
37,33.,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,34.,Yadanziolides T-V 1122 6,NaN
39,35.,Yadanziolides T-V 1222 6,NaN
40,36.,Bruceolline E22 6,NaN
41,37.,Bruceolline F22 6,NaN
42,38.,Bruceine D22 6,Cytotoxic22 6
43,39.,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,40.,Yadanziolide B22 6,Cytotoxic22 6
45,41.,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

In [150]:
df4= df.iloc[26,0]= "26"
df5= df.iloc[28,0]= "28"
df

,0,1,2
0,Column1,Column2,Column3
1,NaN,NaN,NaN
2,S No.,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,1.,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,2.,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,3.,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,4.,"Bruceoside B^1,2",-
7,5.,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,6.,"Soulameanone 1,2",-
9,7.,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,8.,"Bruceolline A 1,2",-
11,9.,"Bruceolline B 1,4",-
12,10.,"Bruceolline C 1,2",-
13,11.,"Bruceolline D 1,2",-
14,12.,"Bruceolline E 1,2",-
15,13.,"Bruceolline F 1,2",-
16,14.,"Bruceolline G 1,2",-
17,15.,"5,11-Dimethoxycanthin-6-one 1,2",-
18,16.,11-Hydroxycanthin-6-one N-oxide 2,-
19,17.,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,18.,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,19.,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,20.,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,21.,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,22.,"Canthin-6-one N –oxide 1,2",-
25,23.,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,26,"glucopyranosylcanthin-6-one 1,2",NaN
27,24.,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,28,"glucopyranosylcanthin-6-one 1,2",NaN
29,25.,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,26.,Bruceollines H-N 122 6,NaN
31,27.,Bruceollines H-N 222 6,NaN
32,28.,Bruceollines H-N 322 6,NaN
33,29.,Bruceollines H-N 422 6,NaN
34,30.,Bruceollines H-N 522 6,NaN
35,31.,Bruceollines H-N 622 6,NaN
36,32.,Bruceollines H-N 722 6,NaN
37,33.,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,34.,Yadanziolides T-V 1122 6,NaN
39,35.,Yadanziolides T-V 1222 6,NaN
40,36.,Bruceolline E22 6,NaN
41,37.,Bruceolline F22 6,NaN
42,38.,Bruceine D22 6,Cytotoxic22 6
43,39.,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,40.,Yadanziolide B22 6,Cytotoxic22 6
45,41.,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

In [151]:
df6= df.iloc[2:]
df6

,0,1,2
2,S No.,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,1.,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,2.,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,3.,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,4.,"Bruceoside B^1,2",-
7,5.,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,6.,"Soulameanone 1,2",-
9,7.,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,8.,"Bruceolline A 1,2",-
11,9.,"Bruceolline B 1,4",-
12,10.,"Bruceolline C 1,2",-
13,11.,"Bruceolline D 1,2",-
14,12.,"Bruceolline E 1,2",-
15,13.,"Bruceolline F 1,2",-
16,14.,"Bruceolline G 1,2",-
17,15.,"5,11-Dimethoxycanthin-6-one 1,2",-
18,16.,11-Hydroxycanthin-6-one N-oxide 2,-
19,17.,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,18.,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,19.,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,20.,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,21.,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,22.,"Canthin-6-one N –oxide 1,2",-
25,23.,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,26,"glucopyranosylcanthin-6-one 1,2",NaN
27,24.,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,28,"glucopyranosylcanthin-6-one 1,2",NaN
29,25.,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,26.,Bruceollines H-N 122 6,NaN
31,27.,Bruceollines H-N 222 6,NaN
32,28.,Bruceollines H-N 322 6,NaN
33,29.,Bruceollines H-N 422 6,NaN
34,30.,Bruceollines H-N 522 6,NaN
35,31.,Bruceollines H-N 622 6,NaN
36,32.,Bruceollines H-N 722 6,NaN
37,33.,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,34.,Yadanziolides T-V 1122 6,NaN
39,35.,Yadanziolides T-V 1222 6,NaN
40,36.,Bruceolline E22 6,NaN
41,37.,Bruceolline F22 6,NaN
42,38.,Bruceine D22 6,Cytotoxic22 6
43,39.,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,40.,Yadanziolide B22 6,Cytotoxic22 6
45,41.,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

In [152]:
df7= df.reset_index(drop= True)
df8= df[0]= range(1, len(df)+ 1)
df

,0,1,2
0,1,Column2,Column3
1,2,NaN,NaN
2,3,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,4,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,5,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,6,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,7,"Bruceoside B^1,2",-
7,8,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,9,"Soulameanone 1,2",-
9,10,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,11,"Bruceolline A 1,2",-
11,12,"Bruceolline B 1,4",-
12,13,"Bruceolline C 1,2",-
13,14,"Bruceolline D 1,2",-
14,15,"Bruceolline E 1,2",-
15,16,"Bruceolline F 1,2",-
16,17,"Bruceolline G 1,2",-
17,18,"5,11-Dimethoxycanthin-6-one 1,2",-
18,19,11-Hydroxycanthin-6-one N-oxide 2,-
19,20,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,21,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,22,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,23,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,24,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,25,"Canthin-6-one N –oxide 1,2",-
25,26,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,27,"glucopyranosylcanthin-6-one 1,2",NaN
27,28,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,29,"glucopyranosylcanthin-6-one 1,2",NaN
29,30,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,31,Bruceollines H-N 122 6,NaN
31,32,Bruceollines H-N 222 6,NaN
32,33,Bruceollines H-N 322 6,NaN
33,34,Bruceollines H-N 422 6,NaN
34,35,Bruceollines H-N 522 6,NaN
35,36,Bruceollines H-N 622 6,NaN
36,37,Bruceollines H-N 722 6,NaN
37,38,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,39,Yadanziolides T-V 1122 6,NaN
39,40,Yadanziolides T-V 1222 6,NaN
40,41,Bruceolline E22 6,NaN
41,42,Bruceolline F22 6,NaN
42,43,Bruceine D22 6,Cytotoxic22 6
43,44,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,45,Yadanziolide B22 6,Cytotoxic22 6
45,46,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

In [153]:
df9= df.iloc[2:]
df9

,0,1,2
2,3,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,4,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,5,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,6,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,7,"Bruceoside B^1,2",-
7,8,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,9,"Soulameanone 1,2",-
9,10,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,11,"Bruceolline A 1,2",-
11,12,"Bruceolline B 1,4",-
12,13,"Bruceolline C 1,2",-
13,14,"Bruceolline D 1,2",-
14,15,"Bruceolline E 1,2",-
15,16,"Bruceolline F 1,2",-
16,17,"Bruceolline G 1,2",-
17,18,"5,11-Dimethoxycanthin-6-one 1,2",-
18,19,11-Hydroxycanthin-6-one N-oxide 2,-
19,20,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,21,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,22,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,23,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,24,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,25,"Canthin-6-one N –oxide 1,2",-
25,26,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,27,"glucopyranosylcanthin-6-one 1,2",NaN
27,28,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,29,"glucopyranosylcanthin-6-one 1,2",NaN
29,30,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,31,Bruceollines H-N 122 6,NaN
31,32,Bruceollines H-N 222 6,NaN
32,33,Bruceollines H-N 322 6,NaN
33,34,Bruceollines H-N 422 6,NaN
34,35,Bruceollines H-N 522 6,NaN
35,36,Bruceollines H-N 622 6,NaN
36,37,Bruceollines H-N 722 6,NaN
37,38,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,39,Yadanziolides T-V 1122 6,NaN
39,40,Yadanziolides T-V 1222 6,NaN
40,41,Bruceolline E22 6,NaN
41,42,Bruceolline F22 6,NaN
42,43,Bruceine D22 6,Cytotoxic22 6
43,44,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,45,Yadanziolide B22 6,Cytotoxic22 6
45,46,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3

,0,1,2
0,1,Column2,Column3
1,2,NaN,NaN
2,3,CHEMICAL CONSTITUENTS,BIOLOGICAL ACTIVITY
3,4,"Bruceine B^1,2","Amebicide, Antimalarial, Antiplasmodial, Cytot..."
4,5,"Bruceine D^1,2","Amebicide, Anticancer, Antileukemic, Antimalar..."
5,6,"Brusatol^1,2","Amebicide, Anticancer, Antifeedant, Antigiardi..."
6,7,"Bruceoside B^1,2",-
7,8,"Yadanziolide A^1,2","Antimalarial, Pesticide3"
8,9,"Soulameanone 1,2",-
9,10,"11-Hydroxycanthin-6-one 1,2","Cytotoxic, Antileukemic"
10,11,"Bruceolline A 1,2",-
11,12,"Bruceolline B 1,4",-
12,13,"Bruceolline C 1,2",-
13,14,"Bruceolline D 1,2",-
14,15,"Bruceolline E 1,2",-
15,16,"Bruceolline F 1,2",-
16,17,"Bruceolline G 1,2",-
17,18,"5,11-Dimethoxycanthin-6-one 1,2",-
18,19,11-Hydroxycanthin-6-one N-oxide 2,-
19,20,"11-hydroxy-1-methoxycanthin-6 1,5",-
20,21,"1-(Hydroxymethyl) ?-carboline 1,5",-
21,22,1-Ethyl- ?–carboline 5,"Antibacterial, CNS-Depressant, Hypotensive, Pe..."
22,23,"9H-pyridol3,4-lindole-1-ethanol 5",-
23,24,"? -Carboline-1-propionic acid 1,5",Camp inhibitor 3
24,25,"Canthin-6-one N –oxide 1,2",-
25,26,11-O-?-D-glucopyranosyl-(1-6)?-D,NaN
26,27,"glucopyranosylcanthin-6-one 1,2",NaN
27,28,5-O-?–Dglucopyranosyl-(1-6)-?-D,NaN
28,29,"glucopyranosylcanthin-6-one 1,2",NaN
29,30,"1-(2’-hydroxymethyl) ?-carboline 1,5",NaN
30,31,Bruceollines H-N 122 6,NaN
31,32,Bruceollines H-N 222 6,NaN
32,33,Bruceollines H-N 322 6,NaN
33,34,Bruceollines H-N 422 6,NaN
34,35,Bruceollines H-N 522 6,NaN
35,36,Bruceollines H-N 622 6,NaN
36,37,Bruceollines H-N 722 6,NaN
37,38,Yadanziolides T-V 10 22 6,Cytotoxic22 6
38,39,Yadanziolides T-V 1122 6,NaN
39,40,Yadanziolides T-V 1222 6,NaN
40,41,Bruceolline E22 6,NaN
41,42,Bruceolline F22 6,NaN
42,43,Bruceine D22 6,Cytotoxic22 6
43,44,"Canthin-6-one 1,7","Antibacterial, Antileukemic, Antimycotic, Anti..."
44,45,Yadanziolide B22 6,Cytotoxic22 6
45,46,"1- Hydroxy-11-methoxycanthin-6-one 1,2",Cytotoxic 3