In [44]:
from rdkit import Chem
import pandas as pd
import numpy as np
from rdkit.Chem import Descriptors, Lipinski

In [45]:
df= pd.read_csv(r"C:\Users\Monsruti Devi\Desktop\DRUG DISCOVERY PROJECT\Bioactivity_preprocessed_data.csv")
df

,assay_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL829584,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL829584,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL830868,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive
3,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive
4,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate
...,...,...,...,...
254,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,52.0,active
255,CHEMBL5550822,CC(C)c1ccc(F)c2[nH]c(C(=O)N3C[C@H]4[C@@H]([C@H...,30.0,active
256,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,14.0,active
257,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,48.0,active
258,CHEMBL5550822,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...,20.0,active

In [ ]:
# def lipinski(smiles, verbose = False):

#     moldata= []

#     for elem in smiles:
#         mol= Chem.MolFromSmiles(elem)
#         moldata.append(mol)

#         baseData = np.arange(1,1)

#         i = 0

#         for mol in moldata:
#             desc_Molwt= Descriptors.MolWt(mol)
#             desc_MolLogP= Descriptors.MolLogP(mol)
#             desc_NumHDonors= Lipinski.NumHDonors(mol)
#             desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)

#             row = np.array([desc_Molwt, desc_MolLogP, desc_NumHDonors, desc_NumHAcceptors])

#             if(i==0):
#                 baseData= row
#             else:
#                 baseData= np.vstack([baseData, row])

#             i = i+1

#             columnNames= ["MW", "LogP", "NumHDonors", "NumHAcceptors"]
#             Descriptors= pd.DataFrame(data= baseData, columns= columnNames )

#             return descriptors

In [47]:
# df_lipinski= lipinski(df.canonical_smiles)

In [ ]:

def lipinski(smiles_list, verbose=False):
    moldata = [Chem.MolFromSmiles(s) for s in smiles_list]  # convert all SMILES

    all_data = []

    for mol in moldata:
        desc_Molwt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_NumHDonors = Lipinski.NumHDonors(mol)
        desc_NumHAcceptors = Lipinski.NumHAcceptors(mol)

        row = [desc_Molwt, desc_MolLogP, desc_NumHDonors, desc_NumHAcceptors]
        all_data.append(row)

        if verbose:
            print(f"Mol: {Chem.MolToSmiles(mol)} -> {row}")

    columnNames = ["MW", "LogP", "NumHDonors", "NumHAcceptors"]
    descriptors = pd.DataFrame(all_data, columns=columnNames)

    return descriptors

In [49]:
df_lipinski= lipinski(df.canonical_smiles)

In [50]:
df_lipinski

          MW     LogP  NumHDonors  NumHAcceptors
0    281.271  1.89262           0              5
1    415.589  3.81320           0              2
2    421.190  2.66050           0              4
3    293.347  3.63080           0              3
4    338.344  3.53900           0              5
..       ...      ...         ...            ...
254  436.512  1.47440           3              4
255  496.583  2.73690           3              4
256  471.985  2.06450           2              4
257  465.594  2.19130           2              4
258  499.534  1.09718           3              5

[259 rows x 4 columns]

In [51]:
df

,assay_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL829584,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate
1,CHEMBL829584,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate
2,CHEMBL830868,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive
3,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive
4,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate
...,...,...,...,...
254,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,52.0,active
255,CHEMBL5550822,CC(C)c1ccc(F)c2[nH]c(C(=O)N3C[C@H]4[C@@H]([C@H...,30.0,active
256,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,14.0,active
257,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,48.0,active
258,CHEMBL5550822,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...,20.0,active

In [53]:
df_combined= pd.concat([df, df_lipinski], axis = 1)
df_combined

,assay_chembl_id,canonical_smiles,standard_value,bioactivity_class,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL829584,Cc1noc(C)c1CN1C(=O)C(=O)c2cc(C#N)ccc21,7200.0,intermediate,281.271,1.89262,0,5
1,CHEMBL829584,O=C1C(=O)N(Cc2ccc(F)cc2Cl)c2ccc(I)cc21,9400.0,intermediate,415.589,3.81320,0,2
2,CHEMBL830868,O=C1C(=O)N(CC2COc3ccccc3O2)c2ccc(I)cc21,13500.0,inactive,421.190,2.66050,0,4
3,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2ccccc21,13110.0,inactive,293.347,3.63080,0,3
4,CHEMBL829584,O=C1C(=O)N(Cc2cc3ccccc3s2)c2c1cccc2[N+](=O)[O-],2000.0,intermediate,338.344,3.53900,0,5
...,...,...,...,...,...,...,...,...
254,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,52.0,active,436.512,1.47440,3,4
255,CHEMBL5550822,CC(C)c1ccc(F)c2[nH]c(C(=O)N3C[C@H]4[C@@H]([C@H...,30.0,active,496.583,2.73690,3,4
256,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,14.0,active,471.985,2.06450,2,4
257,CHEMBL5550822,CC1(C)[C@@H]2[C@@H](C(=O)N[C@H](C=O)C[C@@H]3CC...,48.0,active,465.594,2.19130,2,4
258,CHEMBL5550822,CC(C)(C)[C@H](NC(=O)C(F)(F)F)C(=O)N1C[C@H]2[C@...,20.0,active,499.534,1.09718,3,5

In [ ]:
import numpy as np
def pIC50(input):
    pIC50= []

    for i in input["standard_value_norm"]:
        molar = i*(10** -9) #converts nM to M
        pIC50.append(-np.log10(molar))