In [1]:
import pandas as pd

In [2]:
df= pd.read_csv(r"C:\Users\Monsruti Devi\Documents\DRUG DISCOVERY PROJECT\javanica datase.csv")
df

,0,CHEMICAL CONSTITUENTS,ChEMBL_ID,SMILES,standard_value,units,bioactivity_class
0,1,Bruceine A,CHEMBL250451,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.004,ug.mL-1,Active
1,2,Bruceine B,CHEMBL140809,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.893,ug.mL-1,Active
2,3,Bruceine C,CHEMBL455759,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,0.107,ug.mL-1,Active
3,4,Bruceine D,CHEMBL477693,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.835,ug.mL-1,Active
4,5,Bruceine E,CHEMBL2037038,CC1=C[C@H](O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[...,5000.000,nM,Intermediate
...,...,...,...,...,...,...,...
76,93,Brujavanone J,NaN,NaN,100000.000,nM,Inactive
77,94,Brujavanone K,NaN,NaN,220.000,nM,Active
78,95,Brujavanone L,NaN,NaN,10000.000,nM,Intermediate
79,96,Brujavanone M,NaN,NaN,4900.000,nM,Intermediate
80,97,Brujavanone N,NaN,NaN,100000.000,nM,Inactive

In [3]:
# # Set options to display all rows and columns
# df= pd.set_option('display.max_rows', None)
# df= pd.set_option('display.max_columns', None)
# df= pd.set_option('display.max_colwidth', None) # To prevent truncation of long text in cells

# # Display your DataFrame
# df

In [4]:
df

,0,CHEMICAL CONSTITUENTS,ChEMBL_ID,SMILES,standard_value,units,bioactivity_class
0,1,Bruceine A,CHEMBL250451,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.004,ug.mL-1,Active
1,2,Bruceine B,CHEMBL140809,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.893,ug.mL-1,Active
2,3,Bruceine C,CHEMBL455759,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,0.107,ug.mL-1,Active
3,4,Bruceine D,CHEMBL477693,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.835,ug.mL-1,Active
4,5,Bruceine E,CHEMBL2037038,CC1=C[C@H](O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[...,5000.000,nM,Intermediate
...,...,...,...,...,...,...,...
76,93,Brujavanone J,NaN,NaN,100000.000,nM,Inactive
77,94,Brujavanone K,NaN,NaN,220.000,nM,Active
78,95,Brujavanone L,NaN,NaN,10000.000,nM,Intermediate
79,96,Brujavanone M,NaN,NaN,4900.000,nM,Intermediate
80,97,Brujavanone N,NaN,NaN,100000.000,nM,Inactive

In [5]:
df = df.dropna(subset=["SMILES"])
df

,0,CHEMICAL CONSTITUENTS,ChEMBL_ID,SMILES,standard_value,units,bioactivity_class
0,1,Bruceine A,CHEMBL250451,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.004,ug.mL-1,Active
1,2,Bruceine B,CHEMBL140809,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.893,ug.mL-1,Active
2,3,Bruceine C,CHEMBL455759,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,0.107,ug.mL-1,Active
3,4,Bruceine D,CHEMBL477693,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.835,ug.mL-1,Active
4,5,Bruceine E,CHEMBL2037038,CC1=C[C@H](O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[...,5000.000,nM,Intermediate
6,8,Bruceine H,CHEMBL2037039,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,1300.000,nM,Intermediate
8,10,Bruceine J,CHEMBL399970,CC1=C(O)C(=O)C[C@]2(C)[C@H]3[C@@H](O)[C@H](O)[...,0.742,ug.mL-1,Active
15,17,Javanicolide C,CHEMBL443898,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,100.000,ug.mL-1,Active
16,18,Javanicolide D,CHEMBL503843,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,18.000,ug.mL-1,Active
17,19,Javanicolide E,CHEMBL2037041,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,10000.000,nM,Intermediate
18,20,Javanicolide H,CHEMBL2037037,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,10000.000,nM,Intermediate
19,21,Javanicoside B,CHEMBL503591,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,5.600,ug.mL-1,Active
20,22,Javanicoside C,CHEMBL446883,COC(=O)[C@@]12OC[C@@]34[C@@H](CC5=C(C)C(=O)C(O...,18.000,ug.mL-1,Active
21,23,Javanicoside D,CHEMBL451166,CC/C(=C\C(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](...,89.000,ug.mL-1,Active
22,24,Javanicoside E,CHEMBL508819,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,16.000,ug.mL-1,Active
23,25,Javanicoside F,CHEMBL510116,CC/C(C)=C/C(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H...,50.000,ug.mL-1,Active
31,33,Yadanzioside A,CHEMBL2367704,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,146000.000,nM,Inactive
32,34,Yadanzioside B,CHEMBL2367700,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,4000.000,nM,Intermediate
33,35,Yadanzioside C,CHEMBL499465,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,55000.000,nM,Inactive
34,36,Yadanzioside E,CHEMBL2367698,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,29000.000,nM,Inactive
35,37,Yadanzioside F,CHEMBL509907,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,156000.000,nM,Inactive
36,38,Yadanzioside G,CHEMBL2368538,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,37000.000,nM,Inactive
37,39,Yadanzioside I,CHEMBL506706,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,22.040,ug.mL-1,Active
39,41,Yadanzioside L,CHEMBL2367702,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,10000.000,nM,Intermediate
41,43,Yadanzioside N,CHEMBL2368539,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,49000.000,nM,Inactive
43,45,Yadanzioside P,CHEMBL2367699,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,18000.000,nM,Inactive
44,46,Yadanziolide C,CHEMBL469501,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.216,ug.mL-1,Active
46,50,Brusatol,CHEMBL450464,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,29.190,nM,Active
47,51,Bruceantin,CHEMBL509895,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,514000.000,nM,Inactive
48,52,Bruceantinol,CHEMBL450145,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,50.000,nM,Active
50,54,Bruceoside A,CHEMBL504960,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,29000.000,nM,Inactive
52,56,Bruceoside C,CHEMBL506633,COC(=O)[C@@]12OC[C@]34[C@H](OC(=O)C[C@@H]13)[C...,44000.000,nM,Inactive
53,57,Bruceoside D,CHEMBL505146,CC(C)=CC(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](C...,52000.000,nM,Inactive
54,58,Bruceoside E,CHEMBL450651,CC(C)CC(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](C)...,59000.000,nM,Inactive
59,70,Dehydrobrusatol,CHEMBL2037040,COC(=O)[C@@]12OC[C@@]34[C@@H](CC5=C(C)C(=O)C(O...,10000.000,nM,Intermediate
63,76,Bruceolline H,CHEMBL1922989,CC1(C)C(=O)C(=O)c2c1[nH]c1cc(O)ccc21,10000.000,nM,Intermediate
64,77,Bruceolline I,CHEMBL1922990,CC1(C)c2[nH]c3cc(O)ccc3c2C(=O)[C@@H]1O,10000.000,nM,Intermediate
65,78,Bruceolline J,CHEMBL1922991,CC1(C)c2[nH]c3ccccc3c2C(=O)[C@@H]1O,10000.000,nM,Intermediate
66,79,Bruceolline K,CHEMBL1922992,CC1(C)c2[nH]c3ccccc3c2C(=O)[C@@H]1O[C@@H]1O[C@...,10000.000,nM,Intermediate
67,80,Bruceolline L,CHEMBL1922993,CC(C)[C@@H](O)C(=O)c1c[nH]c2ccccc12,10000.000,nM,Intermediate
68,81,Bruceolline M,CHEMBL1922994,CC(C)(O)C(=O)Cc1cn([C@@H]2O[C@H](CO)[C@@H](O)[...,10000.000,nM,Intermediate
69,82,Bruceolline N,CHEMBL1922995,CC(C)(O)[C@@H](O)C[C@]1(O)C(=O)N([C@@H]2O[C@H]...,10000.000,nM,Intermediate

In [6]:
new_compounds= pd.DataFrame({"CHEMICAL CONSTITUENTS":["Bruceolline E","Bruceolline F","Canthin-6-one"],
                              "ChEMBL_ID": ["CHEMBL1922996","CHEMBL1922997","CHEMBL156897"],
                              "SMILES":["CC1(C)C(=O)C(=O)c2c1[nH]c1ccccc21", "CC(C)(O)[C@@H](O)Cc1cn([C@@H]2O[C@H](CO)[C@@H](O)[C@H](O)[C@H]2O)c2ccccc12", "O=c1ccc2nccc3c4ccccc4n1c23"],
                               "standard_value":["10000.0", "10000.0", "1.11"],
                               "units": ["nM", "nM", "ug.mL-1"],
                               "bioactivity_class": ["Intermediate", "Intermediate", "Active"]})
df= pd.concat([df, new_compounds], ignore_index= True)

In [7]:
df

,0,CHEMICAL CONSTITUENTS,ChEMBL_ID,SMILES,standard_value,units,bioactivity_class
0,1.0,Bruceine A,CHEMBL250451,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.004,ug.mL-1,Active
1,2.0,Bruceine B,CHEMBL140809,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,0.893,ug.mL-1,Active
2,3.0,Bruceine C,CHEMBL455759,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,0.107,ug.mL-1,Active
3,4.0,Bruceine D,CHEMBL477693,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.835,ug.mL-1,Active
4,5.0,Bruceine E,CHEMBL2037038,CC1=C[C@H](O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[...,5000.0,nM,Intermediate
5,8.0,Bruceine H,CHEMBL2037039,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,1300.0,nM,Intermediate
6,10.0,Bruceine J,CHEMBL399970,CC1=C(O)C(=O)C[C@]2(C)[C@H]3[C@@H](O)[C@H](O)[...,0.742,ug.mL-1,Active
7,17.0,Javanicolide C,CHEMBL443898,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,100.0,ug.mL-1,Active
8,18.0,Javanicolide D,CHEMBL503843,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,18.0,ug.mL-1,Active
9,19.0,Javanicolide E,CHEMBL2037041,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,10000.0,nM,Intermediate
10,20.0,Javanicolide H,CHEMBL2037037,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,10000.0,nM,Intermediate
11,21.0,Javanicoside B,CHEMBL503591,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,5.6,ug.mL-1,Active
12,22.0,Javanicoside C,CHEMBL446883,COC(=O)[C@@]12OC[C@@]34[C@@H](CC5=C(C)C(=O)C(O...,18.0,ug.mL-1,Active
13,23.0,Javanicoside D,CHEMBL451166,CC/C(=C\C(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](...,89.0,ug.mL-1,Active
14,24.0,Javanicoside E,CHEMBL508819,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,16.0,ug.mL-1,Active
15,25.0,Javanicoside F,CHEMBL510116,CC/C(C)=C/C(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H...,50.0,ug.mL-1,Active
16,33.0,Yadanzioside A,CHEMBL2367704,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,146000.0,nM,Inactive
17,34.0,Yadanzioside B,CHEMBL2367700,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,4000.0,nM,Intermediate
18,35.0,Yadanzioside C,CHEMBL499465,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,55000.0,nM,Inactive
19,36.0,Yadanzioside E,CHEMBL2367698,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,29000.0,nM,Inactive
20,37.0,Yadanzioside F,CHEMBL509907,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,156000.0,nM,Inactive
21,38.0,Yadanzioside G,CHEMBL2368538,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,37000.0,nM,Inactive
22,39.0,Yadanzioside I,CHEMBL506706,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,22.04,ug.mL-1,Active
23,41.0,Yadanzioside L,CHEMBL2367702,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,10000.0,nM,Intermediate
24,43.0,Yadanzioside N,CHEMBL2368539,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,49000.0,nM,Inactive
25,45.0,Yadanzioside P,CHEMBL2367699,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,18000.0,nM,Inactive
26,46.0,Yadanziolide C,CHEMBL469501,CC1=CC(=O)[C@@H](O)[C@]2(C)[C@H]3[C@@H](O)[C@H...,0.216,ug.mL-1,Active
27,50.0,Brusatol,CHEMBL450464,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,29.19,nM,Active
28,51.0,Bruceantin,CHEMBL509895,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,514000.0,nM,Inactive
29,52.0,Bruceantinol,CHEMBL450145,COC(=O)[C@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)[...,50.0,nM,Active
30,54.0,Bruceoside A,CHEMBL504960,COC(=O)[C@@]12OC[C@]34[C@H]([C@@H](O)[C@@H]1O)...,29000.0,nM,Inactive
31,56.0,Bruceoside C,CHEMBL506633,COC(=O)[C@@]12OC[C@]34[C@H](OC(=O)C[C@@H]13)[C...,44000.0,nM,Inactive
32,57.0,Bruceoside D,CHEMBL505146,CC(C)=CC(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](C...,52000.0,nM,Inactive
33,58.0,Bruceoside E,CHEMBL450651,CC(C)CC(=O)O[C@H]1C(=O)O[C@@H]2C[C@H]3[C@H](C)...,59000.0,nM,Inactive
34,70.0,Dehydrobrusatol,CHEMBL2037040,COC(=O)[C@@]12OC[C@@]34[C@@H](CC5=C(C)C(=O)C(O...,10000.0,nM,Intermediate
35,76.0,Bruceolline H,CHEMBL1922989,CC1(C)C(=O)C(=O)c2c1[nH]c1cc(O)ccc21,10000.0,nM,Intermediate
36,77.0,Bruceolline I,CHEMBL1922990,CC1(C)c2[nH]c3cc(O)ccc3c2C(=O)[C@@H]1O,10000.0,nM,Intermediate
37,78.0,Bruceolline J,CHEMBL1922991,CC1(C)c2[nH]c3ccccc3c2C(=O)[C@@H]1O,10000.0,nM,Intermediate
38,79.0,Bruceolline K,CHEMBL1922992,CC1(C)c2[nH]c3ccccc3c2C(=O)[C@@H]1O[C@@H]1O[C@...,10000.0,nM,Intermediate
39,80.0,Bruceolline L,CHEMBL1922993,CC(C)[C@@H](O)C(=O)c1c[nH]c2ccccc12,10000.0,nM,Intermediate
40,81.0,Bruceolline M,CHEMBL1922994,CC(C)(O)C(=O)Cc1cn([C@@H]2O[C@H](CO)[C@@H](O)[...,10000.0,nM,Intermediate
41,82.0,Bruceolline N,CHEMBL1922995,CC(C)(O)[C@@H](O)C[C@]1(O)C(=O)N([C@@H]2O[C@H]...,10000.0,nM,Intermediate
42,NaN,Bruceolline E,CHEMBL1922996,CC1(C)C(=O)C(=O)c2c1[nH]c1ccccc21,10000.0,nM,Intermediate
43,NaN,Bruceolline F,CHEMBL1922997,CC(C)(O)[C@@H](O)Cc1cn([C@@H]2O[C@H](CO)[C@@H]...,10000.0,nM,Intermediate
44,NaN,Canthin-6-one,CHEMBL156897,O=c1ccc2nccc3c4ccccc4n1c23,1.11,ug.mL-1,Active

In [8]:
df.to_csv("javanica done.csv", index= False)